---
apiVersion: v1
data:
  config.yml: |
    {{- toYaml .Values.config | nindent 4 }}
kind: ConfigMap
metadata:
  name: loggie-operator-config-{{ template "operator.name" . }}
  namespace: {{ .Release.Namespace }}