apiVersion: v1
kind: Service
metadata:
  labels:
    app: loggie-operator
  name: {{ template "operator.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: operator
    port: 9443
    targetPort: 9443
  selector:
    app: loggie-operator
  type: ClusterIP