apiVersion: v1
kind: Service
metadata:
  labels:
    app: loggie
    instance: {{ template "loggie.name" . }}
  name: {{ template "loggie.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  {{- if .Values.servicePorts }}
    {{ toYaml .Values.servicePorts | nindent 4}}
  {{- end }}
  selector:
    app: loggie
    instance: {{ template "loggie.name" . }}
  type: ClusterIP