{
 "title": "Loggie节点指标",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels{namespace=~\"loggie.*\"}, namespace)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_pod_info{}, node)"
    }
   },
   {
    "name": "pod_name",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\", node=\"$node\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "基础指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "cpu limit",
   "type": "gauge",
   "description": "container里面的cpu limit值",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{namespace=\"$namespace\", pod=\"$pod_name\", resource=\"cpu\"}\n)"
    }
   ]
  },
  {
   "title": "cpu使用率",
   "type": "graph",
   "description": "多个核心的总和，会超过100%",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=\"$pod_name\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "memory limit",
   "type": "gauge",
   "description": "container里面的memory limit值",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{namespace=\"$namespace\", pod=\"$pod_name\", resource=\"memory\"}\n)"
    }
   ]
  },
  {
   "title": "容器内存使用情况",
   "type": "graph",
   "description": "容器内存使用情况",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod_name\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "working_set"
    },
    {
     "expr": "sum(container_memory_rss{namespace=\"$namespace\", pod=\"$pod_name\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "rss"
    }
   ]
  },
  {
   "title": "pod网卡发送字节速率",
   "type": "graph",
   "description": "pod网卡发送字节速率",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"$namespace\", pod=~\"$pod_name\"}[1m]))",
     "legendFormat": "{{pod_name}} 发送字节速率"
    }
   ]
  },
  {
   "title": "reload个数",
   "type": "graph",
   "description": "文件系统读速率",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "loggie_reload_total{namespace=\"$namespace\", pod=\"$pod_name\"}",
     "legendFormat": "reload"
    }
   ]
  },
  {
   "title": "goroutine个数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{namespace=\"$namespace\",pod=\"$pod_name\"}",
     "legendFormat": "goroutine"
    }
   ]
  },
  { "title": "采集指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "采集进度（总）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(loggie_filesource_file_offset{namespace=\"$namespace\", pod=\"$pod_name\"})",
     "legendFormat": "total_offset"
    },
    {
     "expr": "sum(loggie_filesource_file_size{namespace=\"$namespace\", pod=\"$pod_name\"})",
     "legendFormat": "total_size"
    }
   ]
  },
  {
   "title": "采集Line QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(loggie_filesource_line_qps{namespace=\"$namespace\", pod=\"$pod_name\"})",
     "legendFormat": "total"
    },
    {
     "expr": "loggie_filesource_line_qps{namespace=\"$namespace\", pod=\"$pod_name\"}",
     "legendFormat": "{{ filename }}"
    }
   ]
  },
  {
   "title": "进程打开的fd个数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{namespace=\"$namespace\", pod=\"$pod_name\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "正在采集的日志文件",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "loggie_filesource_file_offset{namespace=\"$namespace\", pod=\"$pod_name\"}-0",
     "legendFormat": "offset"
    },
    {
     "expr": "loggie_filesource_file_size{namespace=\"$namespace\", pod=\"$pod_name\"}",
     "legendFormat": "size"
    },
    {
     "expr": "loggie_filesource_file_offset{pod=\"$pod_name\"} / loggie_filesource_file_size{pod=\"$pod_name\"}",
     "legendFormat": "读取进度"
    }
   ]
  },
  {
   "title": "匹配的日志文件总数",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(loggie_filewatcher_total_file_count{namespace=\"$namespace\", pod=\"$pod_name\"})"
    }
   ]
  },
  {
   "title": "匹配的文件个数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(loggie_filewatcher_total_file_count{namespace=\"$namespace\", pod=\"$pod_name\"})",
     "legendFormat": "总数"
    },
    {
     "expr": "loggie_filewatcher_total_file_count{namespace=\"$namespace\", pod=\"$pod_name\"}",
     "legendFormat": "source: {{ source }}"
    }
   ]
  },
  {
   "title": "inactive日志文件总数",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(loggie_filewatcher_inactive_file_count{namespace=\"$namespace\", pod=\"$pod_name\"})"
    }
   ]
  },
  {
   "title": "inactive的文件个数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(loggie_filewatcher_inactive_file_count{namespace=\"$namespace\", pod=\"$pod_name\"})",
     "legendFormat": "总数"
    },
    {
     "expr": "loggie_filewatcher_inactive_file_count{namespace=\"$namespace\", pod=\"$pod_name\"}",
     "legendFormat": "source: {{ source }}"
    }
   ]
  },
  {
   "title": "全量日志文件",
   "type": "table-old",
   "description": "不包含ignoreOlder和excludeFiles匹配的日志文件",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "loggie_filewatcher_file_ack_offset{namespace=\"$namespace\", pod=\"$pod_name\"}-0",
     "legendFormat": "ack_offset"
    },
    {
     "expr": "loggie_filewatcher_file_size{namespace=\"$namespace\", pod=\"$pod_name\"}",
     "legendFormat": "size"
    },
    {
     "expr": "loggie_filewatcher_file_ack_offset{namespace=\"$namespace\", pod=\"$pod_name\"} / loggie_filewatcher_file_size{namespace=\"$namespace\", pod=\"$pod_name\"}",
     "legendFormat": "采集进度"
    },
    {
     "expr": "loggie_filewatcher_file_last_modify{namespace=\"$namespace\", pod=\"$pod_name\"}-0",
     "legendFormat": "modify"
    }
   ]
  },
  { "title": "发送指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "发送event QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(loggie_sink_event_qps{namespace=\"$namespace\", pod=\"$pod_name\"})",
     "legendFormat": "total"
    },
    {
     "expr": "loggie_sink_event_qps{namespace=\"$namespace\", pod=\"$pod_name\"}",
     "legendFormat": "pipeline: {{ pipeline }}"
    }
   ]
  },
  {
   "title": "采集发送延迟",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(loggie_filesource_line_qps{namespace=\"$namespace\", pod=\"$pod_name\"}) - sum(loggie_sink_event_qps{namespace=\"$namespace\", pod=\"$pod_name\"})",
     "legendFormat": "延迟：采集-发送"
    },
    {
     "expr": "sum(loggie_filesource_line_qps{namespace=\"$namespace\", pod=\"$pod_name\"})",
     "legendFormat": "采集line qps"
    },
    {
     "expr": "sum(loggie_sink_event_qps{namespace=\"$namespace\", pod=\"$pod_name\"})",
     "legendFormat": "发送event qps"
    }
   ]
  },
  {
   "title": "发送event成功个数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(loggie_sink_success_event{namespace=\"$namespace\", pod=\"$pod_name\"})",
     "legendFormat": "total"
    },
    {
     "expr": "loggie_sink_success_event{namespace=\"$namespace\", pod=\"$pod_name\"}",
     "legendFormat": "source: {{ source }}"
    }
   ]
  },
  {
   "title": "发送event失败个数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(loggie_sink_failed_event{namespace=\"$namespace\", pod=\"$pod_name\"})",
     "legendFormat": "total"
    },
    {
     "expr": "loggie_sink_failed_event{namespace=\"$namespace\", pod=\"$pod_name\"}",
     "legendFormat": "source: {{ source }}"
    }
   ]
  }
 ]
}