{
 "title": "Loggie监控大盘",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels{namespace=~\"loggie.*\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "cpu使用率(TOP10)",
   "type": "graph",
   "description": "多个核心的总和，会超过100%",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}) by(node, namespace, pod))",
     "legendFormat": "{{ node }} | {{ pod }}"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"})",
     "legendFormat": "所有节点总和"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "table",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}) by(node, namespace, pod)"
    }
   ]
  },
  {
   "title": "Memory使用率(TOP10)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\"}) by (node, pod, container))",
     "legendFormat": "{{node}} | {{pod}}"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\"})",
     "legendFormat": "所有节点总和"
    }
   ]
  },
  {
   "title": "Memory使用率(TOP10)",
   "type": "table",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\"}) by (node, pod, container)",
     "legendFormat": "working_set"
    },
    {
     "expr": "sum(container_memory_rss{namespace=\"$namespace\", container!=\"\", image!=\"\"}) by (node, pod, container)-0",
     "legendFormat": "rss"
    }
   ]
  },
  {
   "title": "网卡发送流量(TOP10)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(irate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[2m])) by (node, pod) )",
     "legendFormat": "{{node}} | {{pod}}"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[2m]))",
     "legendFormat": "所有节点总和"
    }
   ]
  },
  {
   "title": "网卡发送速率(TOP10)",
   "type": "table",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 23 },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[2m])) by (node, pod)"
    }
   ]
  },
  {
   "title": "goroutine个数",
   "type": "graph",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(10, go_goroutines{namespace=\"$namespace\"}) by (instance, pod)",
     "legendFormat": "{{ instance }} | {{ pod}}"
    }
   ]
  },
  {
   "title": "goroutine个数(TOP10)",
   "type": "table",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "所有未采集完日志文件",
   "type": "table-old",
   "description": "不包含ignoreOlder和excludeFiles匹配的日志文件",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "loggie_filewatcher_file_ack_offset{status=\"unfinished\"}-0",
     "legendFormat": "ack_offset"
    },
    {
     "expr": "loggie_filewatcher_file_size{status=\"unfinished\"}",
     "legendFormat": "size"
    },
    {
     "expr": "loggie_filewatcher_file_ack_offset{status=\"unfinished\"} / loggie_filewatcher_file_size{status=\"unfinished\"}",
     "legendFormat": "采集进度"
    },
    {
     "expr": "loggie_filewatcher_file_last_modify{status=\"unfinished\"}-0",
     "legendFormat": "modify"
    }
   ]
  }
 ]
}